# Generated by Django 3.2.25 on 2024-06-27 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255, null=True)),
                ('years_old', models.PositiveSmallIntegerField(null=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('year_of_publicity', models.PositiveSmallIntegerField()),
                ('covers', models.CharField(choices=[('soft', 'soft'), ('hard', 'hard'), ('digital', 'digital')], max_length=255)),
                ('language', models.CharField(choices=[('English', 'En'), ('German', 'De'), ('Bulgarian', 'Bg'), ('Spanish', 'Es')], max_length=255)),
                ('genre', models.TextField(choices=[('technical', 'Technical'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror')], max_length=255)),
                ('pages', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.author')),
            ],
        ),
    ]
